name: Merlin
version: ${project.version}
main: me.pigworlddev.merlin.Merlin
api-version: 1.16
authors: [ ThePigStupo ]
commands:
  god:
    description: Makes you invincible
    aliases:
      - invulnerable
  feed:
    description: Hunger no longer
    aliases:
      - food
